from aiogram_dialog import Dialog
from aiogram_dialog.widgets.kbd import Cancel, SwitchTo, Button, Back, Next

from src.custom_widgets.i18n_format import I18NFormat
from src.tgbot.my_wish_lists.wishes.getters import wish_preview_on_creation_getter, does_smth_exists_getter
from src.tgbot.my_wish_lists.wishes.handlers import save_name, save_photos, save_description, save_link_to_marketplace, \
    save_price, on_start_create_wish_dialog, \
    create_wish_handler, set_edit_mode, edit_name, edit_price, edit_link, edit_description, \
    edit_photo, on_start_edit_wish_dialog, set_none_photo, set_none_description, set_none_link, set_none_price
from src.tgbot.my_wish_lists.wishes.states import CreateWishSG, EditWishSG
from src.tgbot.shared.wish_edit_dialog import WishEdit
from src.tgbot.shared.wish_view import WishView

create_wish_dialog = Dialog(
    WishEdit.name_window(
        Cancel(
            I18NFormat('back')
        ),
        handler=save_name,
        state=CreateWishSG.name
    ),
    WishEdit.photo_window(
    Next(
            I18NFormat('skip-step'),
        ),
        Back(
            I18NFormat('back')
        ),
        handler=save_photos,
        state=CreateWishSG.photos
    ),
    WishEdit.description_window(
    Next(
            I18NFormat('skip-step'),
        ),
        Back(
            I18NFormat('back')
        ),
        handler=save_description,
        state=CreateWishSG.description
    ),
    WishEdit.link_window(
        Next(
            I18NFormat('skip-step'),
        ),
        Back(
            I18NFormat('back')
        ),
        handler=save_link_to_marketplace,
        state=CreateWishSG.link_to_marketplace
    ),
    WishEdit.price_window(
        Next(
            I18NFormat('skip-step'),
        ),
        Back(
            I18NFormat('back')
        ),
        handler=save_price,
        state=CreateWishSG.price
    ),
    WishView.preview_wish(
        SwitchTo(
            I18NFormat('edit-name'),
            id='edit_name',
            state=CreateWishSG.name,
            on_click=set_edit_mode
        ),
        SwitchTo(
            I18NFormat('edit-photo'),
            id='edit_photo',
            state=CreateWishSG.photos,
            on_click=set_edit_mode
        ),
        SwitchTo(
            I18NFormat('edit-description'),
            id='edit_description',
            state=CreateWishSG.description,
            on_click=set_edit_mode
        ),
        SwitchTo(
            I18NFormat('edit-link-to-marketplace'),
            id='edit_link_to_marketplace',
            state=CreateWishSG.link_to_marketplace,
            on_click=set_edit_mode
        ),
        SwitchTo(
            I18NFormat('edit-price'),
            id='edit_price',
            state=CreateWishSG.price,
            on_click=set_edit_mode
        ),
        Cancel(
            I18NFormat('cancel-creation')
        ),
        Button(
            I18NFormat('done'),
            id='done_wish_create',
            on_click=create_wish_handler
        ),
        getter=wish_preview_on_creation_getter,
        state=CreateWishSG.preview
    ),
    on_start=on_start_create_wish_dialog
)

edit_wish_dialog = Dialog(
    WishEdit.name_window(
        Cancel(
            I18NFormat('back')
        ),
        handler=edit_name,
        state=EditWishSG.name
    ),
    WishEdit.photo_window(
        Cancel(
            I18NFormat('wish-edit-photo-set-none'),
            id='set_none_wish_photo',
            on_click=set_none_photo,
            when='photo'
        ),
        Cancel(
            I18NFormat('back')
        ),
        handler=edit_photo,
        state=EditWishSG.photos,
        getter=does_smth_exists_getter
    ),
    WishEdit.description_window(
        Cancel(
            I18NFormat('wish-edit-description-set-none'),
            id='set_none_wish_description',
            on_click=set_none_description,
            when='description'
        ),
        Cancel(
            I18NFormat('back')
        ),
        handler=edit_description,
        state=EditWishSG.description,
        getter=does_smth_exists_getter
    ),
    WishEdit.link_window(
        Cancel(
            I18NFormat('wish-edit-link-set-none'),
            id='set_none_wish_link',
            on_click=set_none_link,
            when='link'
        ),
        Cancel(
            I18NFormat('back')
        ),
        handler=edit_link,
        state=EditWishSG.link_to_marketplace,
        getter=does_smth_exists_getter
    ),
    WishEdit.price_window(
        Cancel(
            I18NFormat('wish-edit-price-set-none'),
            id='set_none_wish_price',
            on_click=set_none_price,
            when='price'
        ),
        Cancel(
            I18NFormat('back')
        ),
        handler=edit_price,
        state=EditWishSG.price,
        getter=does_smth_exists_getter
    ),
    on_start=on_start_edit_wish_dialog,
)
