"""add photo field in wish table

Revision ID: 7c063a99fefb
Revises: 61765079452e
Create Date: 2025-01-11 21:34:36.996802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c063a99fefb'
down_revision: Union[str, None] = '61765079452e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('photo', sa.String(), nullable=True))
    op.alter_column('wishes', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishes', 'price',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('wishes', 'photo')
    # ### end Alembic commands ###
