"""add columns for wishes table

Revision ID: 61765079452e
Revises: 30005e18571e
Create Date: 2025-01-09 08:29:06.223798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61765079452e'
down_revision: Union[str, None] = '30005e18571e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('name', sa.String(), nullable=False))
    op.add_column('wishes', sa.Column('description', sa.String(), nullable=True))
    op.add_column('wishes', sa.Column('link_to_marketplace', sa.String(), nullable=True))
    op.add_column('wishes', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'price')
    op.drop_column('wishes', 'link_to_marketplace')
    op.drop_column('wishes', 'description')
    op.drop_column('wishes', 'name')
    # ### end Alembic commands ###
