"""add booking by user

Revision ID: 832d948cefd2
Revises: 7c063a99fefb
Create Date: 2025-01-31 16:46:18.636888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832d948cefd2'
down_revision: Union[str, None] = '7c063a99fefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('is_booked', sa.Boolean(), nullable=False))
    op.add_column('wishes', sa.Column('booked_by_user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'wishes', 'users', ['booked_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.drop_column('wishes', 'booked_by_user_id')
    op.drop_column('wishes', 'is_booked')
    # ### end Alembic commands ###
