"""bug fix

Revision ID: 517b5e6c41ed
Revises: 74901ce831b7
Create Date: 2025-01-02 08:59:11.948365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517b5e6c41ed'
down_revision: Union[str, None] = '74901ce831b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_lists', sa.Column('owner_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('wish_lists_user_id_fkey', 'wish_lists', type_='foreignkey')
    op.create_foreign_key(None, 'wish_lists', 'users', ['owner_id'], ['id'])
    op.drop_column('wish_lists', 'user_id')
    op.drop_constraint('wishes_user_id_fkey', 'wishes', type_='foreignkey')
    op.drop_column('wishes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('wishes_user_id_fkey', 'wishes', 'users', ['user_id'], ['id'])
    op.add_column('wish_lists', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wish_lists', type_='foreignkey')
    op.create_foreign_key('wish_lists_user_id_fkey', 'wish_lists', 'users', ['user_id'], ['id'])
    op.drop_column('wish_lists', 'owner_id')
    # ### end Alembic commands ###
