"""add some columns

Revision ID: 30005e18571e
Revises: 59f3d817d0da
Create Date: 2025-01-08 11:32:20.635804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30005e18571e'
down_revision: Union[str, None] = '59f3d817d0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_lists', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_lists', 'name')
    # ### end Alembic commands ###
